default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %> # Use the environment variable for the host
  username: <%= ENV['DB_USER'] %> # Use the environment variable for the username
  password: <%= ENV['DB_PASSWORD'] %> # Use the environment variable for the password
  port: <%= ENV['DB_PORT'] || 3306 %> # Default to port 3306 if not specified

development:
  <<: *default
  database: galary_space_development

test:
  <<: *default
  database: galary_space_test

production:
  <<: *default
  database: galary_space_production
  username: <%= ENV['DB_USER'] %> # Ensure username and password are set correctly for production
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %> # Ensure host is set for production
